### ISSUE TITLE
Meow preset (like in Massive)

### ISSUE THREAD

**Issue by RustoMCSpit** [a2aaron/nyasynth#9]
If you have the original Massive by Native Instruments, could you listen to it and try emulate that as well?

**Comment by RustoMCSpit** [comment]
Busy rn I'll read the responses you wrote later sorry

**Comment by a2aaron** [comment]
I do not own Massive, but also nyasynth is intended to be reimplementation of meowsynth, so I probably will not do this. Sorry!

**Comment by RustoMCSpit** [comment]
> I do not own Massive, but also nyasynth is intended to be reimplementation of meowsynth, so I probably will not do this. Sorry!

*not massive apologies, trash

**Comment by RustoMCSpit** [comment]
'trash' is the plugin name

**Comment by a2aaron** [comment]
if by trash you mean izotope’s trash2 plugin, then I definitely wouldn’t be able to recreate that—thats a pretty large plugin with a ton of features.

**Comment by RustoMCSpit** [comment]
> if by trash you mean izotope’s trash2 plugin, then I definitely wouldn’t be able to recreate that—thats a pretty large plugin with a ton of features.

no not the whole plugin, just that preset. it changes all sounds to 'meow'
